### ISSUE TITLE
Build error using gradle

### ISSUE THREAD

**Issue by viper9586** [Backendless/Android-SDK#178]
I'm using gradle to build an Backendless app.

`  compile 'com.backendless:android:3.0.6'`

When compiling i get the following error:
```
Error:(34, 41) java: cannot access com.backendless.commons.AbstractBackendlessCollection
  class file for com.backendless.commons.AbstractBackendlessCollection not found
```

The code generating the error is this:
`        BackendlessCollection<T> collection = Backendless.Persistence.of(clazz).find(query);`

The same error appears if i use 
`  compile 'com.backendless:android:3.0.5'`

The build only works if i download the android/java sdk from [https://backendless.com/downloads/](https://backendless.com/downloads/) 

Thank you.

**Comment by ksv510** [comment]
Hello viper9586,

we have released new version, and it will be available soon under version 'com.backendless:backendless:3.0.8.1'. I will notify you, when it will be ready

**Comment by cepvirus** [comment]
It will very greatfull for us to use
On 3 Feb 2016 14:07, "ksv510" <notifications@github.com> wrote:
>
> Hello viper9586,
>
> we have released new version, and it will be available soon under version
'com.backendless:backendless:3.0.8.1'. I will notify you, when it will be
ready

**Comment by ksv510** [comment]
like a work around you can use our repo http://maven.backendless.com/#artifact~backendless_public/com.backendless/backendless/3.0.8

dependencies {
  compile 'com.backendless:backendless:3.0.8'
}

repositories {
  maven {
    url "http://maven.backendless.com/repository/backendless_public"
  }
}

**Comment by viper9586** [comment]
Working. Thanks. Please close this issue :)

**Comment by ksv510** [comment]
now it is available on maven http://mvnrepository.com/artifact/com.backendless/backendless/3.0.8.1
do not use previous versions
