### ISSUE TITLE
Why are you throwing IllegalArgumentException when the environment is Android?

### ISSUE THREAD

**Issue by sunshineo** [Backendless/Android-SDK#190]
Look at this line https://github.com/Backendless/Android-SDK/blob/master/src/com/backendless/Backendless.java#L103

It is ridiculous.
Or if somehow the logic is correct, your choice of wording is ridiculous!

**Comment by scadgek** [comment]
Because in Android you need to pass also an argument of type Context. And that's pretty the same that the error says.

**Comment by sunshineo** [comment]
Please have a look at your guide.
https://backendless.com/documentation/Backendless%20API%20for%20Android.pdf
https://backendless.com/documentation/users/android/users_overview.htm
Can you give me an example?

**Comment by sunshineo** [comment]
Found at https://github.com/Backendless/Android-Samples/blob/e78628f84d9a41f8c5f01b498158b55b70717201/rolesdemo/src/com/backendless/examples/userservice/rolesdemo/ui/LoginActivity.java

I'm guessing it need to be Backendless.initApp( this, application-id, secret-key, version );

**Comment by scadgek** [comment]
There are two ways to call Backendless.initApp(...): one for Java (passing only appId, secretKey and version) and one for Android (passing also a Context, for example, your main Activity).

**Comment by sunshineo** [comment]
I did not see this requirement for Android documented anywhere at all.
https://backendless.com/documentation/users/android/users_requirements.htm

**Comment by scadgek** [comment]
You're right, looks like a drawback in the documentation. Thanks for pointing it out, we shall update it!

**Comment by sunshineo** [comment]
OK. Thank you very much!
I'm moving on to my next problem.
BackendlessException{ code: 'Internal client exception', message: 'null' }

**Comment by markpiller** [comment]
Documentation has been updated

**Comment by markpiller** [comment]
'Internal client exception' occurs when you invoke a synchronous method which does network communication on the main thread. Android does not allow blocking network calls on the main thread. Either create a separate thread and invoke sync calls there, or use the async APIs.

**Comment by sunshineo** [comment]
Thank you @markpiller
