### ISSUE TITLE
Unsafe implementation of the WebViewClient.onReceivedSslError handler

### ISSUE THREAD

**Issue by gitmahmud** [Backendless/Android-SDK#200]
Got this warning from Google play developer account "Your app(s) have an unsafe implementation of the WebViewClient.onReceivedSslError handler. Specifically, the implementation ignores all SSL certificate validation errors, making your app vulnerable to man-in-the-middle attacks. An attacker could change the affected WebView's content, read transmitted data (such as login credentials), and execute code inside the app using JavaScript."

Affected Class : com.backendless.SocialAsyncCallback$1;

**Comment by markpiller** [comment]
You need to upgrade to the latest build of the library. You can get it from the SDK download from our website.

**Comment by bab55z** [comment]
is their any possibility to move the Backendless self hosted server to https with let's encrypt certificate ?

thanks.

**Comment by markpiller** [comment]
@bab55z Yes, you'd need to install an SSL cert on your webserver.

**Comment by bab55z** [comment]
ok thanks, i'll try and give feedback later.
