### ISSUE TITLE
Gradle sync problem with version 3.0.17

### ISSUE THREAD

**Issue by illuzor** [Backendless/Android-SDK#208]
Hello. When i`m adding dependency(compile 'com.backendless:backendless:3.0.17') to build.gradle and trying to sync it causes an error:

`Error:Failed to resolve: weborb:weborbclient:5.1.0.206`

With version 3.0.15.1 no errors.
How to fix this error?

**Comment by markpiller** [comment]
Please use version 3.0.17.1, the problem is resolved in that build.

**Comment by illuzor** [comment]
Thank you. It works
