### ISSUE TITLE
Hostname "XXX.XXX.XXX.XXX" was not verified

### ISSUE THREAD

**Issue by bab55z** [Backendless/Android-SDK#215]
On selfhosted i have Hostname "XXX.XXX.XXX.XXX" was not verified error after switching to https. the javascripts client works fine with that same url but i still get that message on android client. 

Is there any way to disable certificate verification for my ip or how to fix that issue. the client is supposed to work with both http and https out of the box.

Thanks in advance.

**Comment by scadgek** [comment]
Could you please share this problem on support.backendless.com also? Our engineers may try to investigate it there.
