### ISSUE TITLE
google plus login example using depreciated getToken method

### ISSUE THREAD

**Issue by ersin-ertan** [Backendless/Android-SDK#219]
This method GoogleAuthUtil.getToken(context, string, string) which is being used [here](https://github.com/Backendless/Android-SDK/blob/master/samples/LoginWithGooglePlusSDK/app/src/main/java/com/backendless/example/loginwithgoogleplussdk/app/LoginFragment.java#L162), is depreciated.

Can you update the sample to show the new way to login? I've also raised [a relevant issue](http://stackoverflow.com/questions/38497317/auth-googlesigninapi-as-googleauthutil-replacement-for-google-plus-signing) on how to get the token.

**Comment by MSIH** [comment]
Have you tried to just use the Account object that is passed into 
`private void loginInBackendless(final GoogleSignInAccount acct)`

Like this
`token = GoogleAuthUtil.getToken( mainActivity, acct, scopes );`

Come from:
```
GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
loginInBackendless( result.getSignInAccount() );
```

**Comment by ersin-ertan** [comment]
Yes I have, see the link:

> relevant issue

getToken() does not conveniently accept a GoogleSignInAccount, but an Account, and GoogleSignInAccount is not a subtype of Account. However, if you choose to go with the AccountManager route calling getAccountsByType:

> The account type is a string token corresponding to the authenticator and useful domain of the account... The exact string token to use will be published somewhere associated with the authenticator in question.

There is no documentation on this so far, other types look like this 'com.google' so backendless may be using something similar to 'com.backendless' but I am waiting for the official response. This method would also require you to request the missing permission at runtime for Manifest.permission.GET_ACCOUNTS.

**Comment by MSIH** [comment]
Why did you close this? Has it been fixed?
