### ISSUE TITLE
Can't compile 'com.backendless:backendless:3.0.8.2' 

### ISSUE THREAD

**Issue by AliOmari** [Backendless/Android-SDK#222]
My project can't build application with this line of code
compile 'com.backendless:backendless:3.0.8.2' 

it gives me build error.

**Comment by markpiller** [comment]
What does the error say?

**Comment by scadgek** [comment]
The latest version is 3.0.20.1, is there a particular reason you use the old one?

**Comment by AliOmari** [comment]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by AliOmari** [comment]
I copy that line from the website, in quick start tutorial.
i can't determine version number from the package it self.

**Comment by scadgek** [comment]
Could you please specify the URL of this page so that we could put the latest version there?
Also, have you tried changing version to the latest one?

**Comment by AliOmari** [comment]
I'll try it and provide you with result.
Thanks for your quick response.
And i check "Quick start" for android tutorial i think that i put this line from some where else but i can't remember from where.

**Comment by AliOmari** [comment]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2


same error

**Comment by scadgek** [comment]
Can you please try [this StackOverflow solution](http://stackoverflow.com/a/32811133/1813669)?

**Comment by AliOmari** [comment]
I've got this error

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/backendless/AbstractDataPermission.class

**Comment by scadgek** [comment]
Now try to [clean the project](http://stackoverflow.com/questions/33209631/errorexecution-failed-for-task-apptransformclasseswithjarmergingfordebug) and make sure that you're not accidentally linking the Backendless Android SDK multiple times (maybe you're linking it in build.gradle and also in project settings, like from "lib" folder).

**Comment by AliOmari** [comment]
Aha now it's done thank you 👍 
but i have another issue can i told you about it here ?
When i make a request
Backendless.Persistence.save(reviewer, new BackendlessCallback<Reviewer>() {
                @Override
                public void handleResponse(Reviewer reviewerObject) {
                    Log.i("Review", "Got new review from " + reviewer.getEmail());
                }

                @Override
                public void handleFault(BackendlessFault fault) {
                    super.handleFault(fault);
                    System.out.print("error"+fault.toString());
                }
            });

it works fine
But the application crashes and the record registered in the table.
crash report from android studio:

07-28 06:13:33.982 13853-13853/? W/dalvikvm: VFY: unable to resolve static method 20379: Lweborb/management/messaging/DestinationMessageCountWatcher;.getInstance ()Lweborb/management/messaging/DestinationMessageCountWatcher;
07-28 06:13:33.982 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x71 at 0x0005
07-28 06:13:33.982 13853-13853/? I/dalvikvm: Could not find method weborb.management.messaging.DestinationMessageCountWatcher.getInstance, referenced from method weborb.v3types.core.DestinationManager.removeDestination
07-28 06:13:33.982 13853-13853/? W/dalvikvm: VFY: unable to resolve static method 20379: Lweborb/management/messaging/DestinationMessageCountWatcher;.getInstance ()Lweborb/management/messaging/DestinationMessageCountWatcher;
07-28 06:13:33.982 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x71 at 0x0008
07-28 06:13:33.982 13853-13853/? I/dalvikvm: Could not find method weborb.util.spring.SpringObjectFactory.createServiceObject, referenced from method weborb.util.ObjectFactories._createServiceObject
07-28 06:13:33.982 13853-13853/? W/dalvikvm: VFY: unable to resolve static method 21481: Lweborb/util/spring/SpringObjectFactory;.createServiceObject (Ljava/lang/String;)Ljava/lang/Object;
07-28 06:13:33.982 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x71 at 0x001c
07-28 06:13:33.986 13853-13853/? I/dalvikvm: Could not find method weborb.config.StartUpMode.isGAE, referenced from method weborb.config.LoggingConfig.configure
07-28 06:13:33.986 13853-13853/? W/dalvikvm: VFY: unable to resolve static method 20342: Lweborb/config/StartUpMode;.isGAE (I)Z
07-28 06:13:33.986 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x71 at 0x0003
07-28 06:13:33.990 13853-13853/? I/dalvikvm: Could not find method weborb.util.StreamReader.readStream, referenced from method weborb.util.ClassLoaders.loadResourceBytes
07-28 06:13:33.990 13853-13853/? W/dalvikvm: VFY: unable to resolve static method 21266: Lweborb/util/StreamReader;.readStream (Ljava/io/InputStream;)[B
07-28 06:13:33.990 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x71 at 0x0019
07-28 06:13:34.006 13853-13853/? E/dalvikvm: Could not find class 'org.hibernate.proxy.HibernateProxy', referenced from method weborb.writer.MessageWriter.initWriters
07-28 06:13:34.006 13853-13853/? W/dalvikvm: VFY: unable to resolve const-class 2646 (Lorg/hibernate/proxy/HibernateProxy;) in Lweborb/writer/MessageWriter;
07-28 06:13:34.010 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x1c at 0x01cb
07-28 06:13:34.010 13853-13853/? E/dalvikvm: Could not find class 'javax.servlet.http.HttpSession', referenced from method weborb.writer.MessageWriter.writeObject
07-28 06:13:34.010 13853-13853/? W/dalvikvm: VFY: unable to resolve check-cast 2605 (Ljavax/servlet/http/HttpSession;) in Lweborb/writer/MessageWriter;
07-28 06:13:34.010 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x1f at 0x0050
07-28 06:13:34.014 13853-13853/? E/dalvikvm: Could not find class 'weborb.types.jdbc.JDBCResultSet', referenced from method weborb.writer.ResultSetWriter.write
07-28 06:13:34.014 13853-13853/? W/dalvikvm: VFY: unable to resolve new-instance 2933 (Lweborb/types/jdbc/JDBCResultSet;) in Lweborb/writer/ResultSetWriter;
07-28 06:13:34.014 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x22 at 0x0000
07-28 06:13:34.014 13853-13853/? D/dalvikvm: DexOpt: unable to opt direct call 0x52ad at 0x04 in Lweborb/writer/ResultSetWriter;.write
07-28 06:13:34.038 13853-13857/? D/dalvikvm: GC_CONCURRENT freed 315K, 13% free 2963K/3388K, paused 3ms+0ms, total 6ms
07-28 06:13:34.046 13853-13853/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
07-28 06:13:34.046 13853-13853/? I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
07-28 06:13:34.046 13853-13853/? W/dalvikvm: VFY: unable to resolve interface method 14794: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
07-28 06:13:34.046 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
07-28 06:13:34.046 13853-13853/? I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
07-28 06:13:34.046 13853-13853/? W/dalvikvm: VFY: unable to resolve interface method 14798: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
07-28 06:13:34.046 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
07-28 06:13:34.082 13853-13853/? I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
07-28 06:13:34.082 13853-13853/? W/dalvikvm: VFY: unable to resolve virtual method 451: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
07-28 06:13:34.082 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
07-28 06:13:34.082 13853-13853/? I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
07-28 06:13:34.082 13853-13853/? W/dalvikvm: VFY: unable to resolve virtual method 473: Landroid/content/res/TypedArray;.getType (I)I
07-28 06:13:34.082 13853-13853/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002

**Comment by scadgek** [comment]
Can't tell anything from this error log. If you provide a minimal code sample which would reproduce the error then we could help you. And better create a new topic for the new problem, I will now close this one.
