### ISSUE TITLE
method start fence monitoring is throwing  {code '4061' message : IllegalArgumentException cannot find geofences}

### ISSUE THREAD

**Issue by madsngh** [Backendless/Android-SDK#237]

**Comment by scadgek** [comment]
Have you first created GeoFences, as described in [the instruction](https://backendless.com/backend-as-a-service/quick-start-guide-for-backendless-geofencing/)?

**Comment by madsngh** [comment]
got the solution. my server side geotracking was on ! Its working f9 after turning it off .
