### ISSUE TITLE
Internal client exception

### ISSUE THREAD

**Issue by Sirelon** [Backendless/Android-SDK#242]
Hi,
I start to use backendless and I encountered a problem. Each my request throws an exception `BackendlessFault{ code: 'Internal client exception', message: 'https://api.backendless.com/1.1/binary' }`

I know, that this exception occurs if I try to send request in the MainThread. But. It throws anywhere. I tried to use many solutions like execute it on new thread, execute it in AsyncTask and execute it with RxJava. It occurs anywhere. 

I tried to use sync method and async (with AsyncCallback). All the same I get an error. 

I try to init app not in Application class but in Activity. It gives nothing. 
I check my permissions in manifest and there is INTERNET permission and ACCESS_NETWORK_STATE

My phone is connected to Wi-Fi. 

I use version from Maven 3.0.20.1

Hope, you will help me. Thanks.

**Comment by markpiller** [comment]
What is your application id ?

**Comment by Sirelon** [comment]
here 7B577BF7-7958-5C63-FF1A-07E4E6598000


And, I found one thing. In my application i have set app version to 1.1 in the initApp method. But on site i see only v1.

**Comment by scadgek** [comment]
Can you prepare [a minimal example](http://stackoverflow.com/help/mcve) of your app?

**Comment by Sirelon** [comment]
Okay. 
Here is app module with sources. There is trying to login with AsyncCallback. 
App id and android client id are the same with keys on the site.

[app.zip](https://github.com/Backendless/Android-SDK/files/444547/app.zip)

**Comment by scadgek** [comment]
Have you tried changing the `appVersion` parameter to the actual name of your application version (which is most probably `v1`)?

**Comment by Sirelon** [comment]
Wow! 
It is works! Thank you very much!
But this exception is not useful. I think you must throw exception something like "Not valid app version" in the initial step, not when user would send request. 
Anyway, thank you very much! Problem is solved.

**Comment by scadgek** [comment]
I've created a separate issue for that: https://github.com/Backendless/Android-SDK/issues/243
