### ISSUE TITLE
Improve error message when wrong appVersion provided

### ISSUE THREAD

**Issue by scadgek** [Backendless/Android-SDK#243]
Consider the following code:

```
Backendless.initApp( "51783F74-D851-497D-FF41-8F68DAABDB00", "987DB19C-DFF2-60C4-FF24-0C42615B6400", "1.0" );

Map<String, String> bear = new HashMap<>();
Backendless.Data.of( "Bear" ).save( bear );
```

In case version "1.0" doesn't exist, the user received the following error:
`BackendlessException{ code: 'Internal client exception', message: 'https://api.backendless.com/1.0/binary' }`

Need to edit this error message to something like `Application version 1.0 does not exist`.

**Comment by felixdivo** [comment]
Why hasn't this been solved yet?

**Comment by markpiller** [comment]
@felixdivo app versions are being removed in Backendless4, this issue is thus becoming obsolete.

**Comment by scadgek** [comment]
closing due to deprecating v3
