### ISSUE TITLE
Backendless crashes when no Internet connectivity

### ISSUE THREAD

**Issue by icoolguy1995** [Backendless/Android-SDK#273]
Backendless throws error when there's Internet without connectivity. For example it will throw an error while fetching or connecting when using a wifi network which has a failed Internet connection.

**Comment by markpiller** [comment]
This is by design - if there is no internet connectivity, the code throws an exception because this is an error condition - the code cannot communicate with the backend (internet is required for that operation)

**Comment by icoolguy1995** [comment]
But it gives a unpleasant experience, that you were using the app and
suddenly Internet goes out. It just crashes the app.

**Comment by markpiller** [comment]
In order to provide a more pleasant experience, your application must have proper error handling. In this case, you should simply add try/catch blocks for synchronous API or handle error in the asynchronous error handlers.
