### ISSUE TITLE
App crashing on Android SDK version 26 or lower

### ISSUE THREAD

**Issue by balbirsng** [Backendless/Android-SDK#312]
SDK is crashing on Android SDK version 26 or lower; while deleting the notification channel on PushTemplateHelper.java. I am using version 4.4.1

**Comment by scadgek** [comment]
Hello Balbir,
Thank you for reporting the issue! 
We shall definitely look into it in the nearest time. Meanwhile, could you please provide more information: the use-case, the stacktrace and/or error log? The exact steps to reproduce would be just perfect. It should help us identify the problem faster and write an appropriate fix.

**Comment by balbirsng** [comment]
Hi,
   I am using following code to register device.

    @Override
    public void registerDevice() {
        Backendless.Messaging.registerDevice(GCM_SENDER_ID,
BACKENDLESS_CHANNEL);
    }


    when it completes, it crashes at following line in
BackendlessPushService.java

PushTemplateHelper.*deleteNotificationChannel*( context );

Any code using SDK version 4.4.1 will have this crash.
Regards,
Balbir Singh

**Comment by oleg-vyalyh** [comment]
Hi. It was fixed. Please, try latest version from maven repository (>=4.5.0).
