### ISSUE TITLE
Ignored parameters in custom services

### ISSUE THREAD

**Issue by david-all-win-software** [Backendless/Android-SDK#466]
The backend logic is ignored from the function "Backendless.CustomService.invoke" from the android client SDK
![codeless](https://user-images.githubusercontent.com/70285087/91336335-ffba6780-e78e-11ea-825c-15a75a706786.png)
I have configured an "onBoarding" service with a "getPages" function which receives parameters, in iOS and javascript clients I have used "Backendless.CustomService.invoke" with parameters and I have received the correct result, but from android I receive a complete table, ignoring business logic.

Example:
`Backendless.CustomService.invoke("onBoarding", "getPages", arrayOf("pageSize" to "1"), Onboarding::class.java, callback)`

**Comment by david-all-win-software** [comment]
Debugging the http queries, I find that the SDK points to a "/ binary" endpoint, is there any other SDK function to use the RESTFULL endpoint?

**Comment by markpiller** [comment]
I believe the problem is here:
`arrayOf("pageSize" to "1")`
It looks like your service expects two arguments (both integers), one for page size and the other for offset. However, your invocation code doesn't send out two integers. It should be changed to something like this:
`arrayOf(valueOfPageSize, valueOfOffset)`

**Comment by david-all-win-software** [comment]
@markpiller thank you very much
The solution was to send simple variables in the same order that they were created in backendless
Example: 
```
val pageSize = 1
val offset = 2
val params = arrayOf(pageSize,offset)

// or just data like this
val params = arrayOf(1, 2) //first pageSize then offset..
Backendless.CustomService.invoke("onBoarding", "getPages", params, Onboarding::class.java, callback)

```
I would like to know if there is another option to send backendless parameters as key value

**Comment by markpiller** [comment]
If you declare service's input parameter as an object, then you would be sending the argument as a collection of key/value pairs.
